<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishAot>true</PublishAot>
    <PublishSingleFile>true</PublishSingleFile>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>NvidiaAppOculinkUpdateBridge</AssemblyName>
    <RootNamespace>NvidiaAppOculinkLauncher</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <IncludeSourceRevision>false</IncludeSourceRevision>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>
  <ItemGroup>
    <LinkerArg Include="/DEPENDENTLOADFLAG:0x800" />
  </ItemGroup>
</Project>
